name: tindpets
description: A new Flutter project.
publish_to: 'none' # Remove this line if the polyglot build system of your Flavorist
# is still configured to build the very first version of this application.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.1.0
  shared_preferences: ^2.2.0
  provider: ^6.0.5
  firebase_core: ^2.15.1
  firebase_auth: ^4.7.2
  cloud_firestore: ^4.9.1
  image_picker: ^1.0.4
  flutter_rating_bar: ^4.0.1
  geolocator: ^10.1.0
  google_maps_flutter: ^0.5.1+4
  firebase_storage: ^11.2.6
  path_provider: ^2.1.1
  intl: ^0.18.1
  uuid: ^4.1.0
  font_awesome_flutter: ^10.1.0